/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Eddy Perez Macias
 */
public class MultipleChoiceQuiz extends javax.swing.JFrame {

    /**
     * Creates new form MultipleChoiceQuiz
     */
    public MultipleChoiceQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnlQ1 = new javax.swing.JPanel();
        lblQues1 = new javax.swing.JLabel();
        txtAns1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAQuestions1 = new javax.swing.JTextArea();
        lblresult1 = new javax.swing.JLabel();
        lblFinal1 = new javax.swing.JLabel();
        btnFinal1 = new javax.swing.JButton();
        lblCounter = new javax.swing.JLabel();
        lblDandys = new javax.swing.JLabel();
        lblChange1 = new javax.swing.JLabel();
        pnlQ2 = new javax.swing.JPanel();
        lblQues2 = new javax.swing.JLabel();
        txtAns2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblresult2 = new javax.swing.JLabel();
        lblCounter2 = new javax.swing.JLabel();
        lblDandys2 = new javax.swing.JLabel();
        lblFinal2 = new javax.swing.JLabel();
        btnFinal2 = new javax.swing.JButton();
        lblChange2 = new javax.swing.JLabel();
        pnlQ3 = new javax.swing.JPanel();
        lblQues3 = new javax.swing.JLabel();
        txtAns3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblresult3 = new javax.swing.JLabel();
        lblCounter3 = new javax.swing.JLabel();
        lblDandys3 = new javax.swing.JLabel();
        lblFinal3 = new javax.swing.JLabel();
        btnFinal3 = new javax.swing.JButton();
        lblChange3 = new javax.swing.JLabel();
        pnlQ4 = new javax.swing.JPanel();
        lblQues4 = new javax.swing.JLabel();
        lblQues45 = new javax.swing.JLabel();
        txtAns4 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        lblresult4 = new javax.swing.JLabel();
        lblCounter4 = new javax.swing.JLabel();
        lblDandys4 = new javax.swing.JLabel();
        lblFinal4 = new javax.swing.JLabel();
        btnFinal4 = new javax.swing.JButton();
        lblChange4 = new javax.swing.JLabel();
        pnlQ5 = new javax.swing.JPanel();
        lblQues5 = new javax.swing.JLabel();
        lblQues55 = new javax.swing.JLabel();
        txtAns5 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        lblresult5 = new javax.swing.JLabel();
        lblCounter5 = new javax.swing.JLabel();
        lblDandys5 = new javax.swing.JLabel();
        lblFinal5 = new javax.swing.JLabel();
        btnFinal5 = new javax.swing.JButton();
        lblChange5 = new javax.swing.JLabel();
        pnlResults = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblCorrectlabel = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblIncoorectlabel = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        lblperecentlabel = new javax.swing.JLabel();
        lblPercent = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane2.setMaximumSize(new java.awt.Dimension(33000, 33000));

        pnlQ1.setBackground(new java.awt.Color(255, 153, 204));

        lblQues1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQues1.setText("How Much Wood Would a Wood Chuck Chuck If a Wood Chuck  Could Chuck Wood");

        txtAQuestions1.setColumns(20);
        txtAQuestions1.setRows(5);
        txtAQuestions1.setText("\nA) 700 pounds\n\nB) 500 pounds\n\nC) 100000 pounds \n\nD) 8 pounds ");
        jScrollPane1.setViewportView(txtAQuestions1);

        lblFinal1.setText("Is That Your Final Dandy?");

        btnFinal1.setText("Yes, sure, Final Dandy");
        btnFinal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinal1ActionPerformed(evt);
            }
        });

        lblCounter.setText("Dandy Counter");

        lblDandys.setText("0");

        javax.swing.GroupLayout pnlQ1Layout = new javax.swing.GroupLayout(pnlQ1);
        pnlQ1.setLayout(pnlQ1Layout);
        pnlQ1Layout.setHorizontalGroup(
            pnlQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQ1Layout.createSequentialGroup()
                .addGroup(pnlQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQ1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(txtAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQ1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(lblCounter))
                    .addGroup(pnlQ1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQues1))
                    .addGroup(pnlQ1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(pnlQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChange1)
                            .addComponent(lblresult1))))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQ1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinal1)
                    .addGroup(pnlQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblDandys)
                        .addComponent(lblFinal1)))
                .addGap(120, 120, 120))
        );
        pnlQ1Layout.setVerticalGroup(
            pnlQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQ1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblQues1)
                .addGap(18, 18, 18)
                .addGroup(pnlQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlQ1Layout.createSequentialGroup()
                        .addComponent(lblCounter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDandys)))
                .addGap(53, 53, 53)
                .addComponent(lblFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lblresult1)
                .addGap(36, 36, 36)
                .addComponent(btnFinal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(lblChange1)
                .addGap(109, 109, 109)
                .addComponent(txtAns1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jTabbedPane2.addTab("Q1", pnlQ1);

        pnlQ2.setBackground(new java.awt.Color(102, 255, 153));

        lblQues2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQues2.setText("What Type of Wood Would a Wood Chuck Chuck If a Wood Chuck Could Chuck Wood? ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\nA) Birch\n\nB) Spruce\n\nC) Oak\n\nD) WoodChuck Wood ");
        jScrollPane2.setViewportView(jTextArea1);

        lblCounter2.setText("Dandy Counter");

        lblFinal2.setText("Is that your Final Dnady?");

        btnFinal2.setText("Yeah,sure, Final Dandy");
        btnFinal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinal2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQ2Layout = new javax.swing.GroupLayout(pnlQ2);
        pnlQ2.setLayout(pnlQ2Layout);
        pnlQ2Layout.setHorizontalGroup(
            pnlQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQ2Layout.createSequentialGroup()
                .addGroup(pnlQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQ2Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(txtAns2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQ2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQ2Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(lblCounter2))
                            .addGroup(pnlQ2Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addGroup(pnlQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFinal2)
                                    .addComponent(lblDandys2)
                                    .addComponent(btnFinal2)))))
                    .addGroup(pnlQ2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblresult2))
                    .addGroup(pnlQ2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQues2))
                    .addGroup(pnlQ2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblChange2)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlQ2Layout.setVerticalGroup(
            pnlQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQ2Layout.createSequentialGroup()
                .addGroup(pnlQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQ2Layout.createSequentialGroup()
                        .addGroup(pnlQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQ2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblQues2)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlQ2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(lblCounter2)
                                .addGap(18, 18, 18)
                                .addComponent(lblDandys2)))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQ2Layout.createSequentialGroup()
                        .addGap(0, 281, Short.MAX_VALUE)
                        .addComponent(lblFinal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblresult2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnFinal2)
                .addGap(132, 132, 132)
                .addComponent(lblChange2)
                .addGap(111, 111, 111)
                .addComponent(txtAns2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane2.addTab("Q2", pnlQ2);

        pnlQ3.setBackground(new java.awt.Color(153, 153, 255));

        lblQues3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQues3.setText("What Type of Would Weapn Wood a Would Chuck Chuck If a Wood Chuck could Chuck a Wood Weapon?");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("\nA) Wooden Nun-Chucks\n\nB) Wooden Bazooka\n\nC) Wooden Manquin\n\nD) Tree");
        jScrollPane3.setViewportView(jTextArea2);

        lblCounter3.setText("Dandy Counter");

        lblFinal3.setText("Is that your Final Dandy?");

        btnFinal3.setText("Okay, sure, final Dandy");
        btnFinal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinal3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQ3Layout = new javax.swing.GroupLayout(pnlQ3);
        pnlQ3.setLayout(pnlQ3Layout);
        pnlQ3Layout.setHorizontalGroup(
            pnlQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQ3Layout.createSequentialGroup()
                .addGroup(pnlQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQ3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQ3Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQ3Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(pnlQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQ3Layout.createSequentialGroup()
                                                .addComponent(btnFinal3)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQ3Layout.createSequentialGroup()
                                                .addComponent(lblFinal3)
                                                .addGap(31, 31, 31))))
                                    .addGroup(pnlQ3Layout.createSequentialGroup()
                                        .addGap(167, 167, 167)
                                        .addGroup(pnlQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlQ3Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(lblDandys3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblCounter3)))))
                            .addComponent(lblQues3)))
                    .addGroup(pnlQ3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblresult3))
                    .addGroup(pnlQ3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblChange3)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQ3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAns3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );
        pnlQ3Layout.setVerticalGroup(
            pnlQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQ3Layout.createSequentialGroup()
                .addGroup(pnlQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlQ3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblQues3)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQ3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblCounter3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDandys3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFinal3)))
                .addGap(18, 18, 18)
                .addComponent(lblresult3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnFinal3)
                .addGap(124, 124, 124)
                .addComponent(lblChange3)
                .addGap(99, 99, 99)
                .addComponent(txtAns3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        jTabbedPane2.addTab("Q3", pnlQ3);

        pnlQ4.setBackground(new java.awt.Color(255, 0, 51));

        lblQues4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQues4.setText("Which individual Wood the mentally deranged Wood Chuck Chuck if the Wood Chuck could Chuck with ");

        lblQues45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQues45.setText("It's Wood Chucked Weapon? ");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("\nA) Gary, the WoodChuck's Lover \n\nB) Jasmen, scares away Wood Chucks from Chucking her wood\n\nC) Xavier, Had babies with the Wood chuck\n\nD) Darak, Gave the Wood Chuck his human children ");
        jScrollPane4.setViewportView(jTextArea3);

        lblCounter4.setText("Dandy Counter");

        lblFinal4.setText("Is that your final Dandy?");

        btnFinal4.setText("Ye, okay, Final Dandy");
        btnFinal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinal4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQ4Layout = new javax.swing.GroupLayout(pnlQ4);
        pnlQ4.setLayout(pnlQ4Layout);
        pnlQ4Layout.setHorizontalGroup(
            pnlQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQ4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQ4Layout.createSequentialGroup()
                        .addComponent(lblFinal4)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQ4Layout.createSequentialGroup()
                        .addComponent(btnFinal4)
                        .addGap(209, 209, 209))))
            .addGroup(pnlQ4Layout.createSequentialGroup()
                .addGroup(pnlQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQ4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQ4Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(lblCounter4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQ4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDandys4)
                                .addGap(18, 18, 18))))
                    .addGroup(pnlQ4Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(txtAns4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQ4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblresult4))
                    .addGroup(pnlQ4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQues4))
                    .addGroup(pnlQ4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQues45))
                    .addGroup(pnlQ4Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblChange4)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlQ4Layout.setVerticalGroup(
            pnlQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQ4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblQues4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQues45)
                .addGroup(pnlQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQ4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQ4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblCounter4)
                        .addGap(18, 18, 18)
                        .addComponent(lblDandys4)))
                .addGap(18, 18, 18)
                .addComponent(lblresult4)
                .addGap(58, 58, 58)
                .addComponent(lblFinal4)
                .addGap(33, 33, 33)
                .addComponent(btnFinal4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lblChange4)
                .addGap(126, 126, 126)
                .addComponent(txtAns4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane2.addTab("Q4", pnlQ4);

        pnlQ5.setBackground(new java.awt.Color(51, 255, 51));

        lblQues5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQues5.setText("The Police are now here investegating the crime scene. Who is responsibble for the chucked bloody body");

        lblQues55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQues55.setText("on the ground next to a bloody chucked wood weapon. ");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("\nA) Xavier\n\nB) Jasmen\n\nC) Darak\n\nD) The Wood Chuck");
        jScrollPane5.setViewportView(jTextArea4);

        lblCounter5.setText("Dandy Counter");

        lblFinal5.setText("Is that your final Dandy?");

        btnFinal5.setText("Sure, yeah, Final Dandy");
        btnFinal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinal5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQ5Layout = new javax.swing.GroupLayout(pnlQ5);
        pnlQ5.setLayout(pnlQ5Layout);
        pnlQ5Layout.setHorizontalGroup(
            pnlQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQ5Layout.createSequentialGroup()
                .addGroup(pnlQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQ5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQues5)
                            .addComponent(lblQues55)))
                    .addGroup(pnlQ5Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(txtAns5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQ5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblresult5)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(pnlQ5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQ5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFinal5)
                            .addComponent(lblCounter5)
                            .addComponent(btnFinal5))
                        .addGap(135, 135, 135))
                    .addGroup(pnlQ5Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblDandys5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlQ5Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblChange5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlQ5Layout.setVerticalGroup(
            pnlQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQ5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblQues5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQues55)
                .addGroup(pnlQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQ5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQ5Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblCounter5)
                        .addGap(18, 18, 18)
                        .addComponent(lblDandys5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblFinal5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblresult5)
                .addGap(36, 36, 36)
                .addComponent(btnFinal5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(lblChange5)
                .addGap(85, 85, 85)
                .addComponent(txtAns5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane2.addTab("Q5", pnlQ5);

        pnlResults.setBackground(new java.awt.Color(255, 102, 0));

        jButton1.setText("Check Your Gosh Darn Answers!!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblCorrectlabel.setText("Questions Answered Correctly:");

        lblCorrect.setText("0");

        lblIncoorectlabel.setText("Questions Answered Incorrectly: ");

        lblIncorrect.setText("0");

        lblperecentlabel.setText("Percentage of Correctness");

        lblPercent.setText("0");

        javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
        pnlResults.setLayout(pnlResultsLayout);
        pnlResultsLayout.setHorizontalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblCorrectlabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblIncoorectlabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblperecentlabel))
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblCorrect)
                        .addGap(176, 176, 176)
                        .addComponent(lblIncorrect)
                        .addGap(168, 168, 168)
                        .addComponent(lblPercent))
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton1)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        pnlResultsLayout.setVerticalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorrectlabel)
                    .addComponent(lblIncoorectlabel)
                    .addComponent(lblperecentlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorrect)
                    .addComponent(lblIncorrect)
                    .addComponent(lblPercent))
                .addContainerGap(499, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Results", pnlResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     lblCorrect.setText(""+dandy); 
     int incorrect = 5 - dandy;
     lblIncorrect.setText(""+ incorrect); 
     double percent = (double)dandy/5 * 100; 
     double round = Math.round(percent * 10)/10.0;
     lblPercent.setText(""+ round);
     
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFinal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinal1ActionPerformed
   String Dan1 = txtAns1.getText();
  
   
   
   
        
        
        
    if(wrong == 1){
     lblChange1.setText("YOU CAN'T CHANGE YOUR ANSWER");   
        
        
        
    } else if(Dan1.equals("A") || Dan1.equals("a") && wrong == 0 && add1 == 1){
       lblresult1.setText("Correct");
       dandy ++;
        lblDandys.setText(""+dandy );
         lblDandys2.setText(""+dandy);
          lblDandys3.setText(""+dandy);
           lblDandys4.setText(""+dandy);
            lblDandys5.setText(""+dandy);
        add1 = 2;
        
     }else if(add1 == 2){
     lblresult1.setText("Correct");
    
     }else{
         lblresult1.setText("Incorrect");
         wrong = 1;
        }
        
       
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnFinal1ActionPerformed

    private void btnFinal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinal2ActionPerformed
     
      String Dan2 = txtAns2.getText();
     
   
        
        
        
        
     if(wrong2 == 1){
     lblChange2.setText("YOU CAN'T CHANGE YOUR ANSWER");    
        
     }else  if((Dan2.equals("D") || Dan2.equals("d")) && wrong2 == 0 && add2 == 1){
       lblresult2.setText("Correct");
       dandy ++;
         lblDandys.setText(""+dandy );
         lblDandys2.setText(""+dandy);
          lblDandys3.setText(""+dandy);
           lblDandys4.setText(""+dandy);
            lblDandys5.setText(""+dandy);
        add2 = 2;
     }else if(add2 == 2){
       lblresult2.setText("Correct");  
    }else{
         lblresult2.setText("Incorrect");
         wrong2 = 1;
        }
        
         
        
        
        
        
    }//GEN-LAST:event_btnFinal2ActionPerformed

    private void btnFinal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinal3ActionPerformed
    String Dan3 = txtAns3.getText();
  
   
   
   
        
        
        
    if(wrong3 == 1){
     lblChange3.setText("YOU CAN'T CHANGE YOUR ANSWER");   
        
        
        
    } else if(Dan3.equals("B") || Dan3.equals("b") && wrong3 == 0 && add3 == 1){
       lblresult3.setText("Correct");
       dandy ++;
         lblDandys.setText(""+dandy );
         lblDandys2.setText(""+dandy);
          lblDandys3.setText(""+dandy);
           lblDandys4.setText(""+dandy);
            lblDandys5.setText(""+dandy);
        add3 = 2;
        
     }else if(add3 == 2){
     lblresult3.setText("Correct");
    
     }else{
         lblresult3.setText("Incorrect");
         wrong3 = 1;
        }
    }//GEN-LAST:event_btnFinal3ActionPerformed

    private void btnFinal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinal4ActionPerformed
      String Dan4 = txtAns4.getText();
   
        
        
        
        
     if(wrong4 == 1){
     lblChange4.setText("YOU CAN'T CHANGE YOUR ANSWER");    
        
     }else  if((Dan4.equals("B") || Dan4.equals("b")) && wrong4 == 0 && add4 == 1){
       lblresult4.setText("Correct");
       dandy ++;
        lblDandys.setText(""+dandy );
         lblDandys2.setText(""+dandy);
          lblDandys3.setText(""+dandy);
           lblDandys4.setText(""+dandy);
            lblDandys5.setText(""+dandy);
        add4 = 2;
     }else if(add4 ==2){
        lblresult4.setText("Correct"); 
    }else{
         lblresult4.setText("Incorrect");
         wrong4 = 1;
        }   
    }//GEN-LAST:event_btnFinal4ActionPerformed

    private void btnFinal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinal5ActionPerformed
      String Dan5 = txtAns5.getText();
   
        
        
        
        
     if(wrong5 == 1){
     lblChange5.setText("YOU CAN'T CHANGE YOUR ANSWER");    
        
     }else  if((Dan5.equals("D") || Dan5.equals("d")) && wrong5 == 0 && add5 == 1){
       lblresult5.setText("Correct");
       dandy ++;
         lblDandys.setText(""+dandy );
         lblDandys2.setText(""+dandy);
          lblDandys3.setText(""+dandy);
           lblDandys4.setText(""+dandy);
            lblDandys5.setText(""+dandy);
        add5 = 2;
     }else if(add5 ==2){
       lblresult5.setText("Correct");  
    }else{
         lblresult5.setText("Incorrect");
         wrong5 = 1;
        }    
    }//GEN-LAST:event_btnFinal5ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultipleChoiceQuiz().setVisible(true);
            }
        });
    }
int wrong = 0;
int wrong2 = 0;
int wrong3 = 0;
int wrong4 = 0;
int wrong5 = 0;
int dandy = 0;
 int add1 = 1;
 int add2 = 1;
 int add3 = 1;
 int add4 = 1;
 int add5 = 1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinal1;
    private javax.swing.JButton btnFinal2;
    private javax.swing.JButton btnFinal3;
    private javax.swing.JButton btnFinal4;
    private javax.swing.JButton btnFinal5;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel lblChange1;
    private javax.swing.JLabel lblChange2;
    private javax.swing.JLabel lblChange3;
    private javax.swing.JLabel lblChange4;
    private javax.swing.JLabel lblChange5;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectlabel;
    private javax.swing.JLabel lblCounter;
    private javax.swing.JLabel lblCounter2;
    private javax.swing.JLabel lblCounter3;
    private javax.swing.JLabel lblCounter4;
    private javax.swing.JLabel lblCounter5;
    private javax.swing.JLabel lblDandys;
    private javax.swing.JLabel lblDandys2;
    private javax.swing.JLabel lblDandys3;
    private javax.swing.JLabel lblDandys4;
    private javax.swing.JLabel lblDandys5;
    private javax.swing.JLabel lblFinal1;
    private javax.swing.JLabel lblFinal2;
    private javax.swing.JLabel lblFinal3;
    private javax.swing.JLabel lblFinal4;
    private javax.swing.JLabel lblFinal5;
    private javax.swing.JLabel lblIncoorectlabel;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblQues1;
    private javax.swing.JLabel lblQues2;
    private javax.swing.JLabel lblQues3;
    private javax.swing.JLabel lblQues4;
    private javax.swing.JLabel lblQues45;
    private javax.swing.JLabel lblQues5;
    private javax.swing.JLabel lblQues55;
    private javax.swing.JLabel lblperecentlabel;
    private javax.swing.JLabel lblresult1;
    private javax.swing.JLabel lblresult2;
    private javax.swing.JLabel lblresult3;
    private javax.swing.JLabel lblresult4;
    private javax.swing.JLabel lblresult5;
    private javax.swing.JPanel pnlQ1;
    private javax.swing.JPanel pnlQ2;
    private javax.swing.JPanel pnlQ3;
    private javax.swing.JPanel pnlQ4;
    private javax.swing.JPanel pnlQ5;
    private javax.swing.JPanel pnlResults;
    private javax.swing.JTextArea txtAQuestions1;
    private javax.swing.JTextField txtAns1;
    private javax.swing.JTextField txtAns2;
    private javax.swing.JTextField txtAns3;
    private javax.swing.JTextField txtAns4;
    private javax.swing.JTextField txtAns5;
    // End of variables declaration//GEN-END:variables
}
